name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # اجرای خودکار روزانه
  workflow_dispatch:  # قابلیت اجرای دستی

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: nasiri-ma
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "output/*.svg"
